containers:        
    audiobookshelf:
      keywords:
        - requested download
        - failed login
        
    vaultwarden:
    # The next 5 settings override the global settings only for this container
      ntfy_tags: closed_lock_with_key   
      ntfy_priority: 5
      ntfy_topic: security
      attachment_lines: 50     
      notification_cooldown: 2  
      keywords:
        - login
      keywords_with_attachment:                    
        - critical
    # action_keywords will trigger a restart/stop of the container and can only be set per container (vaultwarden might not be the best examlw though)
      action_keywords:    # restart & stop are the only supported actions and have to be specified before every keyword
        - restart: traceback
        - stop:
            regex: (username|password).*incorrect # this is how to set regex patterns for action_keywords
      action_cooldown: 300 # 300s is the default time that has to pass until the next action can be triggered (minimum value is always 60)

    # If you have configured global_keywords and don't need container specific settings you can define the container name and leave the rest blank
    nextcloud:


global_keywords:
  keywords:
    - panic
  keywords_with_attachment:
    - fatal

notifications:                       
  # At least one of the two (Ntfy/Apprise) is required.
  ntfy:
    url: http://your-ntfy-server    # Required. The URL of your Ntfy instance
    topic: loggifly                 # Required. the topic for Ntfy
    token: ntfy-token               # Ntfy token in case you need authentication 
    username: john                  # Ntfy Username+Password in case you need authentication 
    password: 1234                  # Ntfy Username+Password in case you need authentication 
    priority: 3                     # Ntfy priority (1-5)
    tags: kite,mag                  # Ntfy tags/emojis 
  apprise:
    url: "discord://webhook-url"    # Any Apprise-compatible URL (https://github.com/caronc/apprise/wiki)
  
# settings are optional because they all have default values
# These are the default settings
settings:          
  log_level: INFO               # DEBUG, INFO, WARNING, ERROR
  notification_cooldown: 5      # Seconds between alerts for same keyword (per container)
  action_cooldown: 300          # Cooldown period (in seconds) before the next container action can be performed. Maximum is always at least 60s.
  attachment_lines: 20          # Number of Lines to include in log attachments
  multi_line_entries: True      # Monitor and catch multi-line log entries instead of going line by line. 
  reload_config: True        # When the config file is changed the program reloads the config
  disable_start_message: False  # Suppress startup notification
  disable_shutdown_message: False  # Suppress shutdown notification
  disable_config_reload_message: False   # Suppress config reload notification
