services:
  loggifly:
    container_name: loggifly-local
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Local configuration directory mount
      # Create the ./loggifly/config folder and place your config.yaml there
      - ./loggifly/config:/config
    environment:
      - TZ=Europe/Paris
      # Debug notification driver enabled by default for development
      - DEBUG_ENABLED=true

      # Uncomment and configure according to your needs:
      # - NTFY_URL=https://ntfy.sh/your-topic
      # - NTFY_USERNAME=your-username
      # - NTFY_PASSWORD=your-password
      # - APPRISE_URL=discord://webhook_id/webhook_token
      # - WEBHOOK_URL=http://your-webhook-endpoint
      # - WEBHOOK_HEADERS={"Authorization": "Bearer your-token"}
    restart: unless-stopped

    # Optional: custom network to isolate the container
    # networks:
    #   - loggifly-network

# Optional: custom network definition
# networks:
#   loggifly-network:
#     driver: bridge
