# Configuration for testing Container Discovery mode
containers:
  # Leave empty when container_discovery is enabled

global_keywords:
  keywords:
    - error
    - warning
    - failed
  keywords_with_attachment:
    - critical
    - fatal
  action_keywords:                  # Global action keywords for all discovered containers
    - restart: "service crashed"    # Restart container when this keyword is found
    - stop: "fatal error"           # Stop container when this keyword is found

# Advanced container discovery mode
container_discovery:
  enabled: true                     # Enable advanced discovery
  include_patterns:                 # Include containers matching these patterns
    - "*web*"
    - "*api*"
    - "*app*"
    - "*loggifly*"
  exclude_patterns:                 # Exclude containers matching these patterns
    - "*-test"
    - "*-temp"
    - "*-backup"
  required_labels: []               # Containers must have these labels to be monitored
    # Examples:
    # - "monitoring=enabled"        # Uncomment to enable
  exclude_labels:                   # Exclude containers with these labels
    - "monitoring=disabled"
    - "loggifly.exclude=true"
    # Alternative: you can also add the label "loggifly.exclude=true"
    # to the LoggiFly container in your docker-compose.yml
  exclude_system_containers: true   # Exclude system containers

notifications:
  debug:
    enabled: true  # Disable debug mode to avoid displaying system notifications as alerts

settings:
  log_level: DEBUG
  attachment_lines: 10
  notification_cooldown: 2
  disable_start_message: true       # Disable startup messages
  disable_config_reload_message: true  # Disable config reload messages
