# Configuration for testing Container Discovery mode
containers:
  # Leave empty when container_discovery is enabled

global_keywords:
  keywords:
    - error
    - warning
    - failed
  keywords_with_attachment:
    - critical
    - fatal

notifications:
  debug:
    enabled: true  # Disable debug mode to avoid displaying system notifications as alerts

settings:
  log_level: DEBUG
  attachment_lines: 10
  notification_cooldown: 2
  disable_start_message: true       # Disable startup messages
  disable_config_reload_message: true  # Disable config reload messages
